[tool.poetry]
name = "homebot"
version = "2.0.0"
description = "A Telegram bot written in Python"
authors = ["Sebastiano Barezzi <barezzisebastiano@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
python-telegram-bot = "^13.1"
python-dotenv = "^0.15.0"
cowsay = "^3.0"
speedtest-cli = "^2.1.2"
requests = "^2.25.1"
paramiko = "^2.7.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
